import sharp from "sharp";
import { readdir, writeFile } from "node:fs/promises";
import { resolve, join } from "node:path";

const ROOT = resolve(process.cwd(), "public/assets");
const DIRS = ["hero", "fleet", "services", "team"];

async function lqip(absPath) {
  const buf = await sharp(absPath)
    .resize(16, null, { fit: "inside" })
    .jpeg({ quality: 40 })
    .toBuffer();
  return `data:image/jpeg;base64,${buf.toString("base64")}`;
}

const out = {};

for (const dir of DIRS) {
  const abs = join(ROOT, dir);
  const files = (await readdir(abs)).filter((f) => /\.(jpe?g|png|webp)$/i.test(f));
  for (const f of files) {
    const key = `/assets/${dir}/${f}`;
    out[key] = await lqip(join(abs, f));
  }
}

const ts =
  "// Auto-generated by scripts/generate-blur.mjs — do not edit by hand.\n" +
  "export const blurData: Record<string, string> = " +
  JSON.stringify(out, null, 2) +
  ";\n";

await writeFile(resolve("src/lib/blurData.ts"), ts);
console.log(`wrote ${Object.keys(out).length} placeholders → src/lib/blurData.ts`);
